# Generated by Django 4.2.5 on 2023-09-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chifon_alter_ritzypro_color_alter_ritzypro_pricesale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('namescarf', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('pricesale', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('ProductDescription', models.TextField()),
            ],
        ),
   
    ]
