# Generated by Django 4.2.5 on 2023-09-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_woven'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lycra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('namescarf', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('ProductDescription', models.TextField()),
            ],
        ),
    ]
