# Generated by Django 4.2.5 on 2023-09-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_lycra'),
    ]

    operations = [
        migrations.AddField(
            model_name='lycra',
            name='image2',
            field=models.TextField(null=True),
        ),
    ]
