# Generated by Django 4.2.5 on 2023-09-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_linen_remove_lycra_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chifon',
            name='sold',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chifon',
            name='pricesale',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
