# Generated by Django 4.2.5 on 2023-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_home_image2_home_pricesale_home_soldout_home_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('image2', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('namescarf', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('pricesale', models.CharField(blank=True, max_length=255)),
                ('soldout', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
