# Generated by Django 4.2.5 on 2023-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='quic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
