# Generated by Django 4.2.5 on 2023-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_all1'),
    ]

    operations = [
        migrations.AddField(
            model_name='woven',
            name='image2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='woven',
            name='sold',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='all',
            name='quic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chifon',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lycra',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='woven',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='woven',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
