# Generated by Django 4.2.5 on 2023-09-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_all1_remove_woven_sold_alter_all_quic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woven',
            name='quic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='woven',
            name='sold',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
